name = "staffing-api"
main = "src/index.ts"
compatibility_date = "2025-01-05"
node_compat = true
account_id = "7abb63759fda749d9c275e8f4bcdd57f"

[observability]
enabled = true

# Development (local)
[env.development]
# Use .dev.vars for secrets in development

# Production
[env.production]
name = "staffing-esn-api-prod"
workers_dev = false
# routes = ["api.votre-domaine.com/*"]

[[env.production.d1_databases]]
binding = "DB"
database_name = "staffing-esn-db-prod"
database_id = ""  # À remplir après création: npx wrangler d1 create staffing-esn-db-prod

# Database D1 (Development/Local)
[[d1_databases]]
binding = "DB"
database_name = "staffing-db"
database_id = "d05d8775-7871-4f91-8d26-b3a6641441dd"
